path: ./data/grafiti-dataset
train: "C:/Users/istok/Documents/VS_CODE/IB_CSP/data/grafiti-dataset/train/images"
val:   "C:/Users/istok/Documents/VS_CODE/IB_CSP/data/grafiti-dataset/valid/images"
test:  "C:/Users/istok/Documents/VS_CODE/IB_CSP/data/grafiti-dataset/test/images"
names: ["graffiti"]
