model: runs/detect/train2/weights/best.pt       # keep 's'; good balance on 6GB
data: configs/data.yaml
imgsz: 1152                # 1280 may OOM on 6GB; start 1024
epochs: 10                 # you can raise later
batch: 8                   # safe starting batch for 6GB
device: 0                  # <-- force GPU 0
workers: 4                 # dataloader workers on Windows
single_cls: true           # since we collapsed labels
cache: disk                # avoid big RAM caches on CPU
plots: false               # speed up a bit

# reasonable augs (you can re-enable stronger ones later)
mosaic: 0.5
degrees: 10
translate: 0.1
scale: 0.6
shear: 2
perspective: 0.0005
hsv_h: 0.02
hsv_s: 0.4
hsv_v: 0.4
close_mosaic: 10
